### ISSUE TITLE
Site launch checklist

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/liz-portfolio#8]
Forked from the [DataMade Site Launch Checklist](https://github.com/datamade/site-launch-checklist).

## Web Search Indexing
* [x] If you have a staging site, tell the search engine robots not to index you with a robots.txt
* [x] Make sure you allow indexing when you are ready to launch
* [x] Make sure you handle the www subdomain with DNS redirect

## Google Analytics

* [x] Create [Google Analytics](http://www.google.com/analytics/) account
* [x] Hook up the GA Tracking Code (typically in our `analytics_lib.js` file)
* [x] Set up relevant Goals and Funnels
* [x] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en)
* [x] Verify site in Webmaster Tools with DNS TXT record
* [x] Link Webmaster Tools to Google Analytics

## Sharing & Rich Snippets

- [x] Set up general meta tags
 * `<meta name=“description”>`
 * `<meta name=“author”>`
- [x] Set up Facebook meta tags & validate [here](https://developers.facebook.com/tools/debug/)
 * `<meta property=“og:site_name”>`
 * `<meta property=“og:title”>`
 * `<meta property=“og:type”>`
 * `<meta property=“og:description”>`
 * `<meta property=“og:url”>`
 * `<meta property=“og:image”>`
- [x] Set up Twitter meta tags & validate [here](https://cards-dev.twitter.com/validator)
 * `<meta name=“twitter:card”>`
 * `<meta name=“twitter:site”>`
 * `<meta name=“twitter:creator”>`
 * `<meta name=“twitter:description”>` (note that this needs to be under 200 characters)
 * `<meta name=“twitter:title”>`
 * `<meta name=“twitter:url”>`
 * `<meta name=“twitter:image:src”>`

## Mobile Friendliness

Test on various mobile devices:
- [x] scrolling is easy
- [x] nav bar works
- [x] hoverable things are tappable
- [x] charts/maps look ok

## Page Speed
- [x] run the site through https://developers.google.com/speed/pagespeed/insights/

## Miscellaneous Polish
- [x] add favicons, apple touch icons (http://www.favicomatic.com/)
- [x] add 404 & 500 error pages

## Testing

- [ ] Plan for a day of bugfixing. This day should happen after you have added the last features you plan on adding.

## GitHub Readme

If the site is open source, make sure the Readme.md is complete and accurate. 

Here's a few good examples:

- [Geomancer](https://github.com/associatedpress/geomancer/blob/master/README.md)
- [Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/README.md)

The Readme should have the following sections:

- [ ] Overview
- [ ] Setup
- [ ] Running locally
- [ ] Team
- [ ] Errors / Bugs 
- [ ] Pull Requests
- [ ] Copyright and License
